apiVersion: batch/v1
kind: Job
metadata:
  labels:
    batch.kubernetes.io/job-name: asdf
    job-name: asdf
  name: asdf
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/job-name: asdf
        job-name: asdf
    spec:
      containers:
      - image: ghcr.io/kubero-dev/deployer:latest
        imagePullPolicy: Always
        name: asdf
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NAME
          value: example
        - name: APP
          value: example
        - name: PHASE
          value: dev
        - name: PIPELINE
          value: pipelinename
        - name: TAG
          value: registry.yourdomain.com/kapck/example:latest
        - name: SERVICE_ACCOUNT
          value: kpack-sa
        - name: BUILDER
          value: gcr.io/paketo-buildpacks/builder:base
        - name: URL
          value: https://github.com/kubero-dev/template-nodeapp.git
        - name: REVISON
          value: main
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30