---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-auth
  annotations:
    kpack.io/git: git@github.com
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: XXXXX
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-user-pass
  annotations:
    kpack.io/docker: https://registry.yourdomain.com
type: kubernetes.io/basic-auth
stringData:
  username: XXXXXX
  password: XXXXXX
---
  apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-sa
secrets:
  - name: registry-user-pass
  - name: git-ssh-auth
imagePullSecrets:
  - name: registry-user-pass
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-role
rules:
  - apiGroups: ["kpack.io"]
    resources: ["builds", "images"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kpack-role
subjects:
  - kind: ServiceAccount
    name: kpack-sa